 ERROR 2025-03-14 01:54:54,782 log Internal Server Error: /accounts/
Traceback (most recent call last):
  File "c:\Users\Hong\workspace\maplestorage\maplestorage_backend\.venv\lib\site-packages\django\db\models\fields\__init__.py", line 2123, in get_prep_value
    return int(value)
  File "c:\Users\Hong\workspace\maplestorage\maplestorage_backend\.venv\lib\site-packages\django\contrib\auth\models.py", line 438, in __int__
    raise TypeError(
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Hong\workspace\maplestorage\maplestorage_backend\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\Users\Hong\workspace\maplestorage\maplestorage_backend\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Users\Hong\workspace\maplestorage\maplestorage_backend\.venv\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "c:\Users\Hong\workspace\maplestorage\maplestorage_backend\.venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Users\Hong\workspace\maplestorage\maplestorage_backend\.venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "c:\Users\Hong\workspace\maplestorage\maplestorage_backend\.venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "c:\Users\Hong\workspace\maplestorage\maplestorage_backend\.venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "c:\Users\Hong\workspace\maplestorage\maplestorage_backend\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Hong\workspace\maplestorage\maplestorage_backend\accounts\views.py", line 72, in get
    api_key = MapleStoryAPIKey.objects.get(user=request.user).api_key
  File "c:\Users\Hong\workspace\maplestorage\maplestorage_backend\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\Users\Hong\workspace\maplestorage\maplestorage_backend\.venv\lib\site-packages\django\db\models\query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "c:\Users\Hong\workspace\maplestorage\maplestorage_backend\.venv\lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "c:\Users\Hong\workspace\maplestorage\maplestorage_backend\.venv\lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "c:\Users\Hong\workspace\maplestorage\maplestorage_backend\.venv\lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "c:\Users\Hong\workspace\maplestorage\maplestorage_backend\.venv\lib\site-packages\django\db\models\sql\query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "c:\Users\Hong\workspace\maplestorage\maplestorage_backend\.venv\lib\site-packages\django\db\models\sql\query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "c:\Users\Hong\workspace\maplestorage\maplestorage_backend\.venv\lib\site-packages\django\db\models\sql\query.py", line 1555, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "c:\Users\Hong\workspace\maplestorage\maplestorage_backend\.venv\lib\site-packages\django\db\models\sql\query.py", line 1385, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "c:\Users\Hong\workspace\maplestorage\maplestorage_backend\.venv\lib\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
  File "c:\Users\Hong\workspace\maplestorage\maplestorage_backend\.venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "c:\Users\Hong\workspace\maplestorage\maplestorage_backend\.venv\lib\site-packages\django\db\models\fields\__init__.py", line 2125, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x000001787D0C3040>.
